name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: [11,17]
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - uses: burrunan/gradle-cache-action@v1
        name: Build and test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          job-id: jdk${{ matrix.version }}
          arguments: build coverallsJacoco
          gradle-version: wrapper
